name: Test OpenHands AI Action

on:
  push:
    branches: [ main ]
    paths:
      - 'action.yml'
      - '.github/workflows/test-action.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'action.yml'
      - '.github/workflows/test-action.yml'
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test OpenHands AI Action with valid API key
        id: openhands_valid
        uses: ./
        with:
          prompt: "What is 2+2?"
          llm_api_key: ${{ secrets.LLM_API_KEY }}
          log_all_events: "true"
          additional_env: |
            {
              "TEST_VAR": "test_value"
            }

      - name: Verify outputs with valid API key
        run: |
          echo "Task ID: ${{ steps.openhands_valid.outputs.task_id }}"
          echo "Status: ${{ steps.openhands_valid.outputs.status }}"
          echo "Result: ${{ steps.openhands_valid.outputs.result }}"
          
          # Basic validation of outputs
          if [ -z "${{ steps.openhands_valid.outputs.task_id }}" ]; then
            echo "Error: Task ID is empty"
            exit 1
          fi
          
          if [ -z "${{ steps.openhands_valid.outputs.status }}" ]; then
            echo "Error: Status is empty"
            exit 1
          fi

      - name: Test OpenHands AI Action without API key
        id: openhands_invalid
        continue-on-error: true
        uses: ./
        with:
          prompt: "What is 2+2?"
          log_all_events: "true"

      - name: Verify error without API key
        run: |
          if [ "${{ steps.openhands_invalid.outcome }}" != "failure" ]; then
            echo "Error: Action should have failed without API key"
            exit 1
          fi 